import React, { Component } from "react";
import EmployeeList from "./EmployeeList";
class Employee extends Component {
  employees = [
    {
      id: 1,
      first_name: "Perren",
      last_name: "Yesenin",
      email: "pyesenin0@desdev.cn",
      gender: "M",
    },
    {
      id: 2,
      first_name: "Sissie",
      last_name: "Eilert",
      email: "seilert1@deliciousdays.com",
      gender: "F",
    },
    {
      id: 3,
      first_name: "Paulo",
      last_name: "Mellor",
      email: "pmellor2@naver.com",
      gender: "M",
    },
    {
      id: 4,
      first_name: "Sam",
      last_name: "Kirley",
      email: "skirley3@jigsy.com",
      gender: "F",
    },
    {
      id: 5,
      first_name: "Mercy",
      last_name: "Spain-Gower",
      email: "mspaingower4@pinterest.com",
      gender: "F",
    },
    {
      id: 6,
      first_name: "Vyky",
      last_name: "Foucar",
      email: "vfoucar5@hubpages.com",
      gender: "F",
    },
    {
      id: 7,
      first_name: "Michaella",
      last_name: "Jeffree",
      email: "mjeffree6@nyu.edu",
      gender: "F",
    },
    {
      id: 8,
      first_name: "Kacy",
      last_name: "Bridge",
      email: "kbridge7@behance.net",
      gender: "F",
    },
    {
      id: 9,
      first_name: "Spense",
      last_name: "Lebrun",
      email: "slebrun8@hubpages.com",
      gender: "M",
    },
    {
      id: 10,
      first_name: "Levon",
      last_name: "Ivery",
      email: "livery9@tripadvisor.com",
      gender: "M",
    },
    {
      id: 11,
      first_name: "Mignon",
      last_name: "Dulling",
      email: "mdullinga@networkadvertising.org",
      gender: "F",
    },
    {
      id: 12,
      first_name: "Ralina",
      last_name: "Klesel",
      email: "rkleselb@yolasite.com",
      gender: "F",
    },
    {
      id: 13,
      first_name: "Ryon",
      last_name: "Esmead",
      email: "resmeadc@livejournal.com",
      gender: "M",
    },
    {
      id: 14,
      first_name: "Ingmar",
      last_name: "Strangman",
      email: "istrangmand@biblegateway.com",
      gender: "M",
    },
    {
      id: 15,
      first_name: "Costanza",
      last_name: "Hallagan",
      email: "challagane@jiathis.com",
      gender: "F",
    },
    {
      id: 16,
      first_name: "Ignacio",
      last_name: "Danniell",
      email: "idanniellf@msu.edu",
      gender: "M",
    },
    {
      id: 17,
      first_name: "Darrel",
      last_name: "Gaggen",
      email: "dgaggeng@icq.com",
      gender: "M",
    },
    {
      id: 18,
      first_name: "Gratia",
      last_name: "Cutchee",
      email: "gcutcheeh@godaddy.com",
      gender: "F",
    },
    {
      id: 19,
      first_name: "Trueman",
      last_name: "Glass",
      email: "tglassi@drupal.org",
      gender: "M",
    },
    {
      id: 20,
      first_name: "Cassy",
      last_name: "Deery",
      email: "cdeeryj@businessweek.com",
      gender: "F",
    },
    {
      id: 21,
      first_name: "Katuscha",
      last_name: "Stallebrass",
      email: "kstallebrassk@miibeian.gov.cn",
      gender: "F",
    },
    {
      id: 22,
      first_name: "Fleming",
      last_name: "Ainslie",
      email: "fainsliel@mashable.com",
      gender: "M",
    },
    {
      id: 23,
      first_name: "Ali",
      last_name: "Burdas",
      email: "aburdasm@opensource.org",
      gender: "M",
    },
    {
      id: 24,
      first_name: "Alexandr",
      last_name: "Wannes",
      email: "awannesn@accuweather.com",
      gender: "M",
    },
    {
      id: 25,
      first_name: "Hilary",
      last_name: "aManger",
      email: "hamangero@mediafire.com",
      gender: "M",
    },
    {
      id: 26,
      first_name: "Richmond",
      last_name: "Minifie",
      email: "rminifiep@tiny.cc",
      gender: "M",
    },
    {
      id: 27,
      first_name: "Melisande",
      last_name: "Velti",
      email: "mveltiq@intel.com",
      gender: "F",
    },
    {
      id: 28,
      first_name: "Jeromy",
      last_name: "Shevels",
      email: "jshevelsr@amazon.co.jp",
      gender: "M",
    },
    {
      id: 29,
      first_name: "Goldarina",
      last_name: "Perello",
      email: "gperellos@discuz.net",
      gender: "F",
    },
    {
      id: 30,
      first_name: "Ruthie",
      last_name: "Jakoub",
      email: "rjakoubt@imageshack.us",
      gender: "F",
    },
    {
      id: 31,
      first_name: "Berke",
      last_name: "McLugaish",
      email: "bmclugaishu@hud.gov",
      gender: "M",
    },
    {
      id: 32,
      first_name: "Betteanne",
      last_name: "Challice",
      email: "bchallicev@jugem.jp",
      gender: "F",
    },
    {
      id: 33,
      first_name: "Lacee",
      last_name: "Bolesma",
      email: "lbolesmaw@macromedia.com",
      gender: "F",
    },
    {
      id: 34,
      first_name: "Isaac",
      last_name: "Tale",
      email: "italex@wikipedia.org",
      gender: "M",
    },
    {
      id: 35,
      first_name: "Melvin",
      last_name: "Walding",
      email: "mwaldingy@dagondesign.com",
      gender: "M",
    },
    {
      id: 36,
      first_name: "Cristionna",
      last_name: "Spraggon",
      email: "cspraggonz@ehow.com",
      gender: "F",
    },
    {
      id: 37,
      first_name: "Georgia",
      last_name: "Dunmuir",
      email: "gdunmuir10@ow.ly",
      gender: "F",
    },
    {
      id: 38,
      first_name: "Melissa",
      last_name: "Kindley",
      email: "mkindley11@hc360.com",
      gender: "F",
    },
    {
      id: 39,
      first_name: "Puff",
      last_name: "Tearny",
      email: "ptearny12@bluehost.com",
      gender: "M",
    },
    {
      id: 40,
      first_name: "Hillyer",
      last_name: "Offell",
      email: "hoffell13@livejournal.com",
      gender: "M",
    },
    {
      id: 41,
      first_name: "Melisandra",
      last_name: "Synan",
      email: "msynan14@gizmodo.com",
      gender: "F",
    },
    {
      id: 42,
      first_name: "Ros",
      last_name: "Gerling",
      email: "rgerling15@seattletimes.com",
      gender: "F",
    },
    {
      id: 43,
      first_name: "Romona",
      last_name: "Aubery",
      email: "raubery16@tripod.com",
      gender: "F",
    },
    {
      id: 44,
      first_name: "Darcie",
      last_name: "Manchester",
      email: "dmanchester17@gmpg.org",
      gender: "F",
    },
    {
      id: 45,
      first_name: "Lorilyn",
      last_name: "Golson",
      email: "lgolson18@soundcloud.com",
      gender: "F",
    },
    {
      id: 46,
      first_name: "Gallagher",
      last_name: "Stirman",
      email: "gstirman19@gnu.org",
      gender: "M",
    },
    {
      id: 47,
      first_name: "Lin",
      last_name: "Billings",
      email: "lbillings1a@4shared.com",
      gender: "F",
    },
    {
      id: 48,
      first_name: "Tandie",
      last_name: "Giovannini",
      email: "tgiovannini1b@tmall.com",
      gender: "F",
    },
    {
      id: 49,
      first_name: "Cob",
      last_name: "Nairn",
      email: "cnairn1c@rambler.ru",
      gender: "M",
    },
    {
      id: 50,
      first_name: "Rutledge",
      last_name: "Durek",
      email: "rdurek1d@reference.com",
      gender: "M",
    },
  ];
  render() {
    return (
      <div>
        <EmployeeList emp={this.employees} />
      </div>
    );
  }
}

export default Employee;
